### ISSUE TITLE
TypeError: fn is not a function

### ISSUE THREAD

**Issue by willingham** [enGMzizo/copy-dynamodb-table#11]
Issue: Copying fails with the error `TypeError: fn is not a function`
Steps to Reproduce: Run the copy script.
Line causing the error: https://github.com/enGMzizo/copy-dynamodb-table/blob/master/index.js#L188
Traceback:
```
Copied 576957 items/Users/thomas/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^
TypeError: fn is not a function
    at /Users/thomas/node_modules/copy-dynamodb-table/index.js:188:16                                                                                                                     
    at Response.<anonymous> (/Users/thomas/node_modules/copy-dynamodb-table/index.js:254:5)    at Request.<anonymous> (/Users/thomas/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/thomas/node_modules/aws-sdk/lib/sequential_executor.js:105:20) 
    at Request.emit (/Users/thomas/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/thomas/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/thomas/node_modules/aws-sdk/lib/request.js:22:10) 
    at AcceptorStateMachine.runTo (/Users/thomas/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/thomas/node_modules/aws-sdk/lib/state_machine.js:26:10 
    at Request.<anonymous> (/Users/thomas/node_modules/aws-sdk/lib/request.js:38:9)
```

This has happened both at the beginning of a run and 576957 records into a run.  I believe this may be happening when the provisioned throughput is consumed, but am not positive.

**Comment by willingham** [comment]
I can also confirm that this error occurs on line 65 any time that a table is not in the `Active` state.

**Comment by willingham** [comment]
My apologies.  I realize this was user error.
