### ISSUE TITLE
Getting error " Unexpected key 'TableClassSummary' found in params " while running the code.

### ISSUE THREAD

**Issue by nikhilatcompro** [enGMzizo/copy-dynamodb-table#38]
I was trying to replicate a table using the copy-dynamodb-table and encountered this issue.
I copy pasted the demo code present in the README and replaced all the placeholders with the appropriate keys.
As soon as i ran `node ./replicateDB.js` , i got this error:

`UnexpectedParameter: Unexpected key 'TableClassSummary' found in params
    at ParamValidator.fail (C:\Users\default\project\node_modules\aws-sdk\lib\param_validator.js:50:37)
    at ParamValidator.validateStructure (C:\Users\default\project\node_modules\aws-sdk\lib\param_validator.js:78:14)
    at ParamValidator.validateMember (C:\Users\default\project\node_modules\aws-sdk\lib\param_validator.js:89:21)
    at ParamValidator.validate (C:\Users\default\project\node_modules\aws-sdk\lib\param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (C:\Users\default\project\node_modules\aws-sdk\lib\event_listeners.js:132:42)
    at Request.callListeners (C:\Users\default\project\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at callNextListener (C:\Users\default\project\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at C:\Users\default\project\node_modules\aws-sdk\lib\event_listeners.js:86:9
    at finish (C:\Users\default\project\node_modules\aws-sdk\lib\config.js:396:7)
    at C:\Users\default\project\node_modules\aws-sdk\lib\config.js:414:9 {
  code: 'UnexpectedParameter',
  time: 2022-09-22T11:17:32.658Z
}
{
  Table: {
    AttributeDefinitions: [ [Object] ],
    TableName: 'BackupTable',
    KeySchema: [ [Object] ],
    TableClassSummary: { TableClass: 'STANDARD' },
    BillingMode: 'PAY_PER_REQUEST'
  }
}`

**Comment by Lekha30** [comment]
yes I am also facing the same issue. Any updates please?

**Comment by Lekha30** [comment]
@nikhilatcompro , was your issue fixed?
