### ISSUE TITLE
Module crashes when copying tables where item count is a multiple of 25

### ISSUE THREAD

**Issue by swac** [enGMzizo/copy-dynamodb-table#7]
When copying a table that happened to have exactly 700 elements, the module crashed with the following error:

```
Copied 675 items{ ValidationException: 1 validation error detected: Value '{prod-checkinresponses=[]}' at 'requestItems' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1]
    at Request.extractError (<PROJECT_DIR>/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (<PROJECT_DIR>/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (<PROJECT_DIR>/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (<PROJECT_DIR>/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (<PROJECT_DIR>/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (<PROJECT_DIR>/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at <PROJECT_DIR>/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (<PROJECT_DIR>/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (<PROJECT_DIR>/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (<PROJECT_DIR>/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: '1 validation error detected: Value \'{prod-checkinresponses=[]}\' at \'requestItems\' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1]',
  code: 'ValidationException',
  time: 2018-03-15T23:05:03.272Z,
  requestId: '<REQUEST ID>',
  statusCode: 400,
  retryable: false,
  retryDelay: 29.387693618990397 }
```

Other tables copied over just fine. After changing the `Limit` field passed to `scan` in the module code from 25 to 24, the copy succeeded. It seems there's a bug that occurs when the item count is a multiple of the limit, which in this case is 25.

**Comment by enGMzizo** [comment]
Unable to reproduce this bug
